browser=chrome
headless=false
base.url=https://the-internet.herokuapp.com
timeout.seconds=25
demo.delay.millis=1000

form.username=tomsmith
form.password=SuperSecretPassword!
invalid.username=wrongUser
invalid.password=wrongPassword
basic.auth.username=admin
basic.auth.password=admin

path.login=/login
path.basic.auth=/basic_auth
path.alerts=/javascript_alerts
path.checkboxes=/checkboxes
path.dropdown=/dropdown
path.upload=/upload
path.dynamic.loading=/dynamic_loading/1
path.disappearing.elements=/disappearing_elements
path.hovers=/hovers
path.broken.images=/broken_images
