login.success.message=You logged into a secure area!
login.failure.message=Your username is invalid!
logout.message=You logged out of the secure area!
secure.area.heading=Secure Area
login.page.heading=Login Page

alert.accept.result=You successfully clicked an alert
confirm.dismiss.result=You clicked: Cancel
prompt.input=InternetBot Prompt
prompt.result.prefix=You entered:

dropdown.option.count=3
dropdown.option.one=Option 1
dropdown.option.two=Option 2

upload.page.heading=File Uploader
upload.supported.file=sample-upload.txt
upload.unsupported.file=unsupported-upload.exe

dynamic.loaded.message=Hello World!
basic.auth.success.message=Congratulations! You must have the proper credentials.
hover.profile.name=user1
alert.page.heading=JavaScript Alerts
alert.confirm.accept.result=You clicked: Ok
alert.prompt.dismiss.result=You entered: null
checkbox.count=2
dropdown.default.option=Please select an option
upload.success.heading=File Uploaded!
dynamic.page.heading=Dynamically Loaded Page Elements
dynamic.start.button=Start
disappearing.minimum.links=4
hover.figure.count=3
hover.profile.two=user2
hover.profile.three=user3
broken.image.count=2
total.image.count=3
internet.page.title=The Internet
